name: Merge

on: 
  pull_request:
    branches:
      - master

jobs:
  dev_deploy:
    name: Deploy to Dev
    runs-on: ubuntu-latest

    steps: 
      - name: Set env variables
        run: |
          echo ::set-env name=ACCOUNT_ID::${{ secrets.ACCOUNT_ID }}
          echo ::set-env name=S3_BUCKET::${{ secrets.S3_BUCKET }}
          echo ::set-env name=PROJECT::${{ secrets.PROJECT }}
          echo ::set-env name=REGION::${{ secrets.REGION }}
          echo ::set-env name=AWS_ACCESS_KEY_ID::${{ secrets.AWS_ACCESS_KEY_ID }}
          echo ::set-env name=AWS_SECRET_ACCESS_KEY:${{ secrets.AWS_SECRET_ACCESS_KEY }}
          echo ::set-env name=DEPLOY_ENV::"enhanced-travel-screening-dev"
          echo ::set-env name=MERGE_BRANCH::"master"
          echo ::set-env name=GIT_LOCAL_BRANCH::${{ github.head_ref }}     

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
            
      - name: Pipeline Build
        run: make pipeline-build
      
      - name: Pipeline Push
        run: make gh-pipeline-push
      
      - name: Deploy Prep
        run: make gh-pipeline-deploy-prep

      - name: Deploy Version
        run: make gh-pipeline-deploy-version
